export const articulos = [
  {
    id: 'patria',
    titulo: 'COLOMBIA: UNA NACIÓN QUE DEBE RECONSTRUIR SU FUTURO ',
    imagen: 'public/imagenes/nacion.jpg',
    texto: 'COLOMBIA: UNA NACIÓN QUE DEBE RECONSTRUIR SU FUTURO .',
    contenido: 'Colombia se enfrenta a una crisis silenciosa que amenaza su futuro: una caída drástica en el nacimiento. Entre 2020 y 2024, 841,000 niños nacieron menos de lo previsto. Esta cifra no es un número simple: coincide con todas las ciudades, como Cúcuta o Pereira, para la desaparición demográfica.\n\nEsta caída no solo responde a factores biológicos o económicos, sino también a una transformación profunda de la cultura que devalúa el estado de la madre, disuelve a la familia y transforma el individualismo en la norma.\n\nHoy en día, los niveles de fertilidad de Colombia han caído a 1.63 niños por mujer. Nos coloca entre países con menor natalidad en América Latina, y nos atrae un destino preocupante: el envejecimiento acelerado de nuestra población.\n\nCada año habrá menos jóvenes, trabajadores más pequeños, soldados más pequeños, colombianos más pequeños que quieran criar su patria. Y al mismo tiempo, habrá una adicción más antigua, mayor, mayor presión sobre el sistema que ya muestra grietas.\n\nEste problema no es solo financiero. Es existencial. Debido a que no hay cultura sin hijos, no hay herencia, no hay nación. Una anciana Colombia sin nacimiento es Colombia, que está destinada a desaparecer lentamente bajo el peso de su indiferencia.\n\nNo podemos permitirlo.\n\nCada niño nacido es un acto de resistencia. Cada familia que decide crecer desafía el discurso descendente. Rotar esta tendencia no es solo una tarea estatal: es el deber patriótico de todos.\n\nEs hora de recuperar el valor de la vida, el orgullo de la familia, la alegría de construir un hogar. No hay más conformismo. Ya no hay la importación de ideologías que atacen nuestras raíces.\n\nColombia debe poblarse. Colombia debe multiplicarse. Colombia debe volver a creer en el futuro.\n\n¡Salva a Colombia! Puebla la patria, forja la nación.\n\n📢 Únete a renacimiento nacional.\n🔗 canal de propaganda RNC: https://t.me/PropagandaResurgimientoNacional\n🔗 rnc grupo del filtro: https://t.me/FiltroNacional.'
  },
  {
    id: 'retorno',
    titulo: 'COLOMBIA: UN SISTEMA EDUCATIVO OBSOLETO',
    imagen: 'public/imagenes/educacion.png',
    texto: 'COLOMBIA: UN SISTEMA EDUCATIVO OBSOLETO.',
    contenido: 'Colombia tiene un sistema educativo que no enfrenta los retos actuales. A medida que el mundo progresa a ritmo acelerado, nuestros jóvenes continúan atrapados en un modelo educativo del siglo XIX. Un modelo que incentiva la memorización, penaliza la creatividad y transforma el razonamiento crítico en un peligro. No se instruye en la construcción del país, sino en la obediencia.\n\nNuestras instituciones educativas no están educando a ciudadanos libres, conscientes o patriotas. Están produciendo trabajadores leales, componentes intercambiables de un sistema que no son de su propiedad. La prioridad no es instruir para cambiar la realidad, sino capacitarse para superar pruebas vacías. Clases desvinculadas del mundo real, docentes cansados, talento malgastado. Y por encima de todo, una estructura que sostiene a la juventud dormida, subordinada y preparada para acatar intereses ajenos.\n\nEste modelo ya no está disponible. No podemos continuar capacitándonos para el fracaso en grupo. La educación debe convertirse en el impulsor de la soberanía del país, no en su impedimento. Colombia requiere una nueva institución educativa: una que impulse la vocación de servicio, que potencie la personalidad, que indique tecnología con objetivo y disciplina, y que inculque amor a la nación. Una formación práctica, contemporánea y genuinamente colombiana.\n\nNuestros jóvenes no constituyen instrumentos económicos para exportar. Son el núcleo del país. No podemos tolerar que continúen siendo modelados por un sistema que carece de fe en ellos. Es momento de desmantelar los vínculos del pasado y desbloquear el potencial de una generación preparada para dirigir, generar y proteger su nación.\n\n¡Transformar la enseñanza es salvaguardar a Colombia!\n¡Deja de construir manos económicas para el foráneo!\n¡Desarrollemos mentes autónomas y corazones patrios al servicio del país!\n\n📢 Únete a renacimiento nacional.\n🔗 canal de propaganda RNC: https://t.me/PropagandaResurgimientoNacional\n🔗 rnc grupo del filtro: https://t.me/FiltroNacional.'

  },
  {
    id: 'resurgimiento',
    titulo: 'COLOMBIA: LA TIERRA SE MUERE Y NADIE LLORA',
    imagen: 'public/imagenes/campo.png',
    texto: 'COLOMBIA: LA TIERRA SE MUERE Y NADIE LLORA',
    contenido: 'Colombia está perdiendo su territorio, y junto a él, su espíritu. A medida que los políticos se enriquecen y los intereses foráneos adquieren hectáreas como si fueran baratijas, el campesino de Colombia se encuentra en la opresión del olvido. No cuenta con respaldo. No posee confianza. No es justa. A pesar de todo, continúa sembrando, produciendo y alimentando a una nación que le da la espalda.\n\nLa comida que se encuentra en tu mesa no surge en los centros comerciales, ni en las avenidas repletas de iluminación. Surge en el terreno. En el terreno que es laborada por manos humildes, moldeadas por el sol y fortalecidas por la indiferencia del Estado. No obstante, esa tierra se extingue. Se degrada, se deteriora, se comercializa, y nadie llora. Ninguna persona oye el grito del productor local que batalla contra la pobreza, el desamparo y la amenaza incesante del despojo.\n\nNo solo se refiere a la economía. Es cuestión de dignidad. La soberanía de una nación no se establece, se fomenta. Y inicia en el terreno. En cada semilla autóctona, en cada propiedad protegida, en cada agricultor resguardado. No podemos dejar que las grandes corporaciones adquieran lo que debería estar en manos de Colombia. No podemos continuar recompensando al delincuente y desestimando al que labora en la tierra.\n\nColombia requiere regresar al campo. Es necesario recuperar su conexión con su raíz más profunda. Es momento de conceder subsidios al que genera, no al que importa. Seguridad al que siembra, no al que amenaza. Tierras para el pueblo, no para el capital extranjero. Si abandonamos el campo, abandonamos la patria. Y un país sin campo es un país condenado a depender, a mendigar, a desaparecer.\n\n¡Defender el campo es defender la patria!\n¡Colombia no se vende, Colombia se cultiva!\n¡La tierra es del pueblo, y debe volver a sus manos! \n\n📢 Únete a renacimiento nacional.\n🔗 canal de propaganda RNC: https://t.me/PropagandaResurgimientoNacional\n🔗 rnc grupo del filtro: https://t.me/FiltroNacional.'

  }
];
